framework:
    notifier:
        chatter_transports:
            # telegram: '%env(TELEGRAM_DSN)%'
            
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'chat/telegram']
            high: ['email', 'chat/telegram']
            medium: ['email', 'chat/telegram']
            low: ['email', 'chat/telegram']
        admin_recipients:
            - { email: "lukameteenk@gmail.com" }
